### ISSUE TITLE
BrowsableAPIRenderer.render assumes url_for is not None

### ISSUE THREAD

**Issue by Patman64** [tomchristie/flask-api#40]
I've encountered this exception:
```
Traceback (most recent call last):
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask\app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask_api\app.py", line 58, in make_response
    rv = self.response_class(rv, headers=headers, status=status_or_headers)
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask_api\response.py", line 17, in __init__
    content = renderer.render(content, media_type, **options)
  File "C:\Users\100496078\Source\panda-insights\panda_api\env\lib\site-packages\flask_api\renderers.py", line 104, in render
    endpoint = request.url_rule.endpoint
AttributeError: 'NoneType' object has no attribute 'endpoint'
```
This is due to the line:
```
endpoint = request.url_rule.endpoint
```
[As documented in Flask's API docs](http://flask.pocoo.org/docs/0.10/api/#flask.Request.url_rule), `url_for` may be `None` in some situations (e.g. for a 404 handler).

Here's a simple piece of demo code to show the bug in action:
```python
from flask.ext.api import FlaskAPI

app = FlaskAPI(__name__)

@app.errorhandler(404)
def not_found(error):
    return {}

app.run(debug=True)
```

**Comment by jacebrowning** [comment]
I'm assuming you meant `url_rule` in the title and body of your comment?

**Comment by Patman64** [comment]
@jacebrowning Yup, my mistake. Title and body corrected.

**Comment by mppavese** [comment]
@jacebrowning Has this since been addressed? Having the same issues when accounting for erroneous routes.

**Comment by jacebrowning** [comment]
Not that I'm aware of. A pull request would be appreciated!

**Comment by Avinash-Raj** [comment]
I added neccessary 404 handler but it still shows this error.
