### ISSUE TITLE
Support for non-English string

### ISSUE THREAD

**Issue by jacktan1991** [tomchristie/flask-api#53]
I rewrite the `notes` in `example.py`

```python
notes = {
    0: '购物',
    1: 'build the codez',
    2: 'paint the door',
}
```

I get an exception: `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 16: ordinal not in range`

**Comment by jacebrowning** [comment]
What version of Python? Try adding a source encoding comment: https://www.python.org/dev/peps/pep-0263/

**Comment by jacktan1991** [comment]
Python2.7, I have tried to add _utf-8_ encoding comment. Here is my [example.py](https://gist.github.com/jacktan1991/4a6fc5ba88f1d06443c8aa587ab03bdd).

<script src="https://gist.github.com/jacktan1991/4a6fc5ba88f1d06443c8aa587ab03bdd.js"></script>

 It's a running time error:
```
Traceback (most recent call last):
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask_api/app.py", line 58, in make_response
    rv = self.response_class(rv, headers=headers, status=status_or_headers)
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask_api/response.py", line 17, in __init__
    content = renderer.render(content, media_type, **options)
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask_api/renderers.py", line 101, in render
    mock_content = mock_renderer.render(data, mock_media_type, indent=4)
  File "/Users/jacktan/workspace/.flask-api/lib/python2.7/site-packages/flask_api/renderers.py", line 72, in render
    return json.dumps(data, cls=JSONEncoder, ensure_ascii=False, indent=indent)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 1: ordinal not in range(128)
```

**Comment by jacebrowning** [comment]
A few more things to try:

- Add `from __future__ import unicode_literals` to the top of your imports.
- Fork `flask-api` to `import simplejson as json`: https://simplejson.readthedocs.org/en/latest/#character-encodings

**Comment by jacktan1991** [comment]
It works now!!

**Comment by jacebrowning** [comment]
What all was required to make it work? Do we need to make any code changes in the package or example?

**Comment by jacktan1991** [comment]
Just follow your steps
* Add a source encoding comment  `# -*- coding: utf-8 -*-`
* Add `from __future__ import unicode_literals`

The runnable version:https://gist.github.com/jacktan1991/4a6fc5ba88f1d06443c8aa587ab03bdd#file-example_v2-py

**Comment by jacebrowning** [comment]
Thanks! That will be helpful as an example to others.
